services:
  server:
    build: .
    container_name: ciiccte-server
    command: uv run fastapi dev src/main.py --host 0.0.0.0   
    ports:
      - "8000:8000"
    networks:
      - db
    volumes:
    # Se cargan estos datos del host en modo read only para detectar a los usuarios
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
networks:
  db:
    name: db-net
    external: true
